Name:           ros-lunar-filters
Version:        1.8.1
Release:        0%{?dist}
Summary:        ROS filters package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/filters
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-lunar-pluginlib
Requires:       ros-lunar-rosconsole
Requires:       ros-lunar-roscpp
Requires:       ros-lunar-roslib
BuildRequires:  ros-lunar-catkin >= 0.5.68
BuildRequires:  ros-lunar-pluginlib
BuildRequires:  ros-lunar-rosconsole
BuildRequires:  ros-lunar-roscpp
BuildRequires:  ros-lunar-roslib
BuildRequires:  ros-lunar-rostest

%description
This library provides a standardized interface for processing data as a sequence
of filters. This package contains a base class upon which to build specific
implementations as well as an interface which dynamically loads filters based on
runtime parameters.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/lunar" \
        -DCMAKE_PREFIX_PATH="/opt/ros/lunar" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/lunar

%changelog
* Tue Apr 25 2017 Tully Foote <tfoote@willowgarage.com> - 1.8.1-0
- Autogenerated by Bloom

* Fri Apr 07 2017 Tully Foote <tfoote@willowgarage.com> - 1.8.0-0
- Autogenerated by Bloom

* Thu Mar 16 2017 Tully Foote <tfoote@willowgarage.com> - 1.7.5-1
- Autogenerated by Bloom

* Thu Mar 16 2017 Tully Foote <tfoote@willowgarage.com> - 1.7.5-0
- Autogenerated by Bloom

* Mon Mar 13 2017 Tully Foote <tfoote@willowgarage.com> - 1.7.4-0
- Autogenerated by Bloom

